apiVersion: v1
kind: Service
metadata:
  name: des-http
  labels:
    app: des-http
spec:
  selector:
    app: des-http
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
